version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
    ports:
      - "8022:8000"
    volumes:
      - ./app:/app
      - ./entrypoint.sh:/app/entrypoint.sh 
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
