version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    command: ["/app/entrypoint.sh", "gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]

volumes:
  db_data:
